Reading and Writing Data in Text Format

In [44]:
# parsing/data loading: data loading and interperting it
# different funtcions to read tabular data: https://wesmckinney.com/book/accessing-data#tbl-table_parsing_functions

# The optional argumnets of these functions may fall into few of these categories:
# indexing
# Type inference and data conversion
# Date and time parsing
# Iterating
# Unclean data issues

import pandas as pd
import numpy as np

df = pd.read_csv("cereal.csv")

In [45]:
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [46]:
# sometimes a file may not have a header row. header = None, provides indexed header
pd.read_csv("cereal.csv", header=None)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
1,100% Bran,N,C,70,4,1,130,10,5,6,280,25,3,1,0.33,68.402973
2,100% Natural Bran,Q,C,120,3,5,15,2,8,8,135,0,3,1,1,33.983679
3,All-Bran,K,C,70,4,1,260,9,7,5,320,25,3,1,0.33,59.425505
4,All-Bran with Extra Fiber,K,C,50,4,0,140,14,8,0,330,25,3,1,0.5,93.704912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Triples,G,C,110,2,1,250,0,21,3,60,25,3,1,0.75,39.106174
74,Trix,G,C,110,1,1,140,0,13,12,25,25,2,1,1,27.753301
75,Wheat Chex,R,C,100,3,1,230,3,17,3,115,25,1,1,0.67,49.787445
76,Wheaties,G,C,100,3,1,200,3,17,3,110,25,1,1,1,51.592193
77,Wheaties Honey Gold,G,C,110,2,1,200,1,16,8,60,25,1,1,0.75,36.187559

In [47]:
# To provide header names we use names=["",""]. 
pd.read_csv("cereal.csv", header=None, names=list("abcdefghijklmnop"))
# if enough column names are not provided then last columns will get the names and starting columns will not

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p
0,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
1,100% Bran,N,C,70,4,1,130,10,5,6,280,25,3,1,0.33,68.402973
2,100% Natural Bran,Q,C,120,3,5,15,2,8,8,135,0,3,1,1,33.983679
3,All-Bran,K,C,70,4,1,260,9,7,5,320,25,3,1,0.33,59.425505
4,All-Bran with Extra Fiber,K,C,50,4,0,140,14,8,0,330,25,3,1,0.5,93.704912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Triples,G,C,110,2,1,250,0,21,3,60,25,3,1,0.75,39.106174
74,Trix,G,C,110,1,1,140,0,13,12,25,25,2,1,1,27.753301
75,Wheat Chex,R,C,100,3,1,230,3,17,3,115,25,1,1,0.67,49.787445
76,Wheaties,G,C,100,3,1,200,3,17,3,110,25,1,1,1,51.592193
77,Wheaties Honey Gold,G,C,110,2,1,200,1,16,8,60,25,1,1,0.75,36.187559

In [48]:
# if we want particular column to become the index of the DataFrame: "index_col="
pd.read_csv("cereal.csv", index_col="rating")

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups
rating,,,,,,,,,,,,,,,
68.402973,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33
33.983679,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00
59.425505,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33
93.704912,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50
34.384843,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39.106174,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75
27.753301,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00
49.787445,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67
51.592193,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00
36.187559,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75

In [50]:
# if hierachical indexing krna h ie., more then one columns then pass it as list
pd.read_csv("cereal.csv",index_col=["name","rating"])

,,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups
name,rating,,,,,,,,,,,,,,
100% Bran,68.402973,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33
100% Natural Bran,33.983679,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00
All-Bran,59.425505,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33
All-Bran with Extra Fiber,93.704912,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50
Almond Delight,34.384843,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Triples,39.106174,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75
Trix,27.753301,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00
Wheat Chex,49.787445,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67
Wheaties,51.592193,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00
Wheaties Honey Gold,36.187559,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75

In [56]:
# In some cases we do not have specific delimiter(separator) 
# \s+: one or more whitespace character. sep="\s+" 
pd.read_csv("cereal.csv",sep=",")

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [58]:
# to skip consideration of some "ROWs"
pd.read_csv("cereal.csv",skiprows=np.arange(70))

,Total Corn Flakes,G,C,110,2,1,200,0,21,3,35,100,3.1,1.1,1.2,38.839746
0,Total Raisin Bran,G,C,140,3,1,190,4,15,14,230,100,3,1.5,1.00,28.592785
1,Total Whole Grain,G,C,100,3,1,200,3,16,3,110,100,3,1.0,1.00,46.658844
2,Triples,G,C,110,2,1,250,0,21,3,60,25,3,1.0,0.75,39.106174
3,Trix,G,C,110,1,1,140,0,13,12,25,25,2,1.0,1.00,27.753301
4,Wheat Chex,R,C,100,3,1,230,3,17,3,115,25,1,1.0,0.67,49.787445
5,Wheaties,G,C,100,3,1,200,3,17,3,110,25,1,1.0,1.00,51.592193
6,Wheaties Honey Gold,G,C,110,2,1,200,1,16,8,60,25,1,1.0,0.75,36.187559

In [61]:
# Missing data: empty string or NA or Null
pd.isna(df).value_counts()

name   mfr    type   calories  protein  fat    sodium  fiber  carbo  sugars  potass  vitamins  shelf  weight  cups   rating
False  False  False  False     False    False  False   False  False  False   False   False     False  False   False  False     77
Name: count, dtype: int64

In [91]:
# to specify missing values in your data: na_values="some string to treated as null"
df_nan = pd.read_csv("cereal.csv", na_values=["R",110], skiprows=np.arange(60))
df_nan

,Raisin Nut Bran,G,C,100,3,2,140,2.5,10.5,8,140.1,25,3.1,1,0.5,39.703400
0,Raisin Squares,K,C,90.0,2,0,0,2,15,6,NaN,25,3,1.00,0.50,55.333142
1,Rice Chex,NaN,C,NaN,1,0,240,0,23,2,30.0,25,1,1.00,1.13,41.998933
2,Rice Krispies,K,C,NaN,2,0,290,0,22,3,35.0,25,1,1.00,1.00,40.560159
3,Shredded Wheat,N,C,80.0,2,0,0,3,16,0,95.0,0,1,0.83,1.00,68.235885
4,Shredded Wheat 'n'Bran,N,C,90.0,3,0,0,4,19,0,140.0,0,1,1.00,0.67,74.472949
5,Shredded Wheat spoon size,N,C,90.0,3,0,0,3,20,0,120.0,0,1,1.00,0.67,72.801787
6,Smacks,K,C,NaN,2,1,70,1,9,15,40.0,25,2,1.00,0.75,31.230054
7,Special K,K,C,NaN,6,0,230,1,16,3,55.0,25,1,1.00,1.00,53.131324
8,Strawberry Fruit Wheats,N,C,90.0,2,0,15,3,15,5,90.0,25,2,1.00,1.00,59.363993
9,Total Corn Flakes,G,C,NaN,2,1,200,0,21,3,35.0,100,3,1.00,1.00,38.839746
10,Total Raisin Bran,G,C,140.0,3,1,190,4,15,14,230.0,100,3,1.50,1.00,28.592785
11,Total Whole Grain,G,C,100.0,3,1,200,3,16,3,NaN,100,3,1.00,1.00,46.658844
12,Triples,G,C,NaN,2,1,250,0,21,3,60.0,25,3,1.00,0.75,39.106174
13,Trix,G,C,NaN,1,1,140,0,13,12,25.0,25,2,1.00,1.00,27.753301
14,Wheat Chex,NaN,C,100.0,3,1,230,3,17,3,115.0,25,1,1.00,0.67,49.787445
15,Wheaties,G,C,100.0,3,1,200,3,17,3,NaN,25,1,1.00,1.00,51.592193
16,Wheaties Honey Gold,G,C,NaN,2,1,200,1,16,8,60.0,25,1,1.00,0.75,36.187559

In [92]:
pd.isna(df_nan).sum(axis=1).sum()

13

In [96]:
# to disable any default setting by pandas for considering the null values: keep_default_na = False
df_nan = pd.read_csv("cereal.csv", keep_default_na=False, na_values=["K"]).head(10)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.00,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.00,1.00,33.983679
2,All-Bran,NaN,C,70,4,1,260,9.0,7.0,5,320,25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,NaN,C,50,4,0,140,14.0,8.0,0,330,25,3,1.00,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.00,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.00,0.75,29.509541
6,Apple Jacks,NaN,C,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562
8,Bran Chex,R,C,90,2,1,200,4.0,15.0,6,125,25,1,1.00,0.67,49.120253
9,Bran Flakes,P,C,90,3,0,210,5.0,13.0,5,190,25,3,1.00,0.67,53.313813

In [106]:
df_nan.isna()

,Raisin Nut Bran,G,C,100,3,2,140,2.5,10.5,8,140.1,25,3.1,1,0.5,39.703400
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
12,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
14,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False

In [107]:
# different NA sentinels can be specified for each column as dictionary
sentinels = {"mfr":["R","K"], "shelf":1}
df_nan = pd.read_csv("cereal.csv", na_values=sentinels)
df_nan

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3.0,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3.0,1.0,1.00,33.983679
2,All-Bran,NaN,C,70,4,1,260,9.0,7.0,5,320,25,3.0,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,NaN,C,50,4,0,140,14.0,8.0,0,330,25,3.0,1.0,0.50,93.704912
4,Almond Delight,NaN,C,110,2,2,200,1.0,14.0,8,-1,25,3.0,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3.0,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2.0,1.0,1.00,27.753301
74,Wheat Chex,NaN,C,100,3,1,230,3.0,17.0,3,115,25,NaN,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,NaN,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,NaN,1.0,0.75,36.187559

In [108]:
# Other important functions for csv: https://wesmckinney.com/book/accessing-data#tbl-table_read_csv_function

Reading Text Files in Pieces

In [110]:
# to maek pandas display compact, we can mention the no. of rows to use
pd.options.display.max_rows = 10

In [111]:
pd.read_csv("cereal.csv")

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [115]:
# if you want to read only a small number of rows
pd.read_csv("cereal.csv", nrows=10)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.00,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.00,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.00,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.00,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.00,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562
8,Bran Chex,R,C,90,2,1,200,4.0,15.0,6,125,25,1,1.00,0.67,49.120253
9,Bran Flakes,P,C,90,3,0,210,5.0,13.0,5,190,25,3,1.00,0.67,53.313813

In [121]:
chunker = pd.read_csv("cereal.csv", chunksize=10)

In [122]:
type(chunker)

pandas.io.parsers.readers.TextFileReader

Writing Data to Text Format

In [125]:
# csv format text can be shown by using to_csv 
data = pd.read_csv("cereal.csv").head(10)
data

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.00,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.00,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.00,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.00,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.00,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562
8,Bran Chex,R,C,90,2,1,200,4.0,15.0,6,125,25,1,1.00,0.67,49.120253
9,Bran Flakes,P,C,90,3,0,210,5.0,13.0,5,190,25,3,1.00,0.67,53.313813

In [126]:
data.to_csv("cereal.csv")

In [127]:
!type cereal.csv

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.0,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.5,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.0,1.0,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562
8,Bran Chex,R,C,90,2,1,200,4.0,15.0,6,125,25,1,1.0,0.67,49.120253
9,Bran Flakes,P,C,90,3,0,210,5.0,13.0,5,190,25,3,1.0,0.67,53.313813

In [131]:
import sys
data.to_csv(sys.stdout, sep="|") # sep should be a one character

|name|mfr|type|calories|protein|fat|sodium|fiber|carbo|sugars|potass|vitamins|shelf|weight|cups|rating
0|100% Bran|N|C|70|4|1|130|10.0|5.0|6|280|25|3|1.0|0.33|68.402973
1|100% Natural Bran|Q|C|120|3|5|15|2.0|8.0|8|135|0|3|1.0|1.0|33.983679
2|All-Bran|K|C|70|4|1|260|9.0|7.0|5|320|25|3|1.0|0.33|59.425505
3|All-Bran with Extra Fiber|K|C|50|4|0|140|14.0|8.0|0|330|25|3|1.0|0.5|93.704912
4|Almond Delight|R|C|110|2|2|200|1.0|14.0|8|-1|25|3|1.0|0.75|34.384843
5|Apple Cinnamon Cheerios|G|C|110|2|2|180|1.5|10.5|10|70|25|1|1.0|0.75|29.509541
6|Apple Jacks|K|C|110|2|0|125|1.0|11.0|14|30|25|2|1.0|1.0|33.174094
7|Basic 4|G|C|130|3|2|210|2.0|18.0|8|100|25|3|1.33|0.75|37.038562
8|Bran Chex|R|C|90|2|1|200|4.0|15.0|6|125|25|1|1.0|0.67|49.120253
9|Bran Flakes|P|C|90|3|0|210|5.0|13.0|5|190|25|3|1.0|0.67|53.313813

In [132]:
# Null values appear as empty string "". If you want some representation, na_rep = ""
data.to_csv(sys.stdout, sep="|", na_rep="NULLL")

|name|mfr|type|calories|protein|fat|sodium|fiber|carbo|sugars|potass|vitamins|shelf|weight|cups|rating
0|100% Bran|N|C|70|4|1|130|10.0|5.0|6|280|25|3|1.0|0.33|68.402973
1|100% Natural Bran|Q|C|120|3|5|15|2.0|8.0|8|135|0|3|1.0|1.0|33.983679
2|All-Bran|K|C|70|4|1|260|9.0|7.0|5|320|25|3|1.0|0.33|59.425505
3|All-Bran with Extra Fiber|K|C|50|4|0|140|14.0|8.0|0|330|25|3|1.0|0.5|93.704912
4|Almond Delight|R|C|110|2|2|200|1.0|14.0|8|-1|25|3|1.0|0.75|34.384843
5|Apple Cinnamon Cheerios|G|C|110|2|2|180|1.5|10.5|10|70|25|1|1.0|0.75|29.509541
6|Apple Jacks|K|C|110|2|0|125|1.0|11.0|14|30|25|2|1.0|1.0|33.174094
7|Basic 4|G|C|130|3|2|210|2.0|18.0|8|100|25|3|1.33|0.75|37.038562
8|Bran Chex|R|C|90|2|1|200|4.0|15.0|6|125|25|1|1.0|0.67|49.120253
9|Bran Flakes|P|C|90|3|0|210|5.0|13.0|5|190|25|3|1.0|0.67|53.313813

In [135]:
# rows and colunmns appear by default. They can be disabled by marking them false
data.to_csv(sys.stdout, index=False, header=False)

100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.0,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.5,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.0,1.0,33.174094
Basic 4,G,C,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562
Bran Chex,R,C,90,2,1,200,4.0,15.0,6,125,25,1,1.0,0.67,49.120253
Bran Flakes,P,C,90,3,0,210,5.0,13.0,5,190,25,3,1.0,0.67,53.313813

In [139]:
# if only want some specific columns then write
data.to_csv(sys.stdout, index=False, columns=["mfr","rating"])

mfr,rating
N,68.402973
Q,33.983679
K,59.425505
K,93.704912
R,34.384843
G,29.509541
K,33.174094
G,37.038562
R,49.120253
P,53.313813

In [141]:
import csv   # csv module
f = open("cereal.csv")
reader = csv.reader(f)

In [142]:
for line in reader:
    print(line)

['', 'name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups', 'rating']
['0', '100% Bran', 'N', 'C', '70', '4', '1', '130', '10.0', '5.0', '6', '280', '25', '3', '1.0', '0.33', '68.402973']
['1', '100% Natural Bran', 'Q', 'C', '120', '3', '5', '15', '2.0', '8.0', '8', '135', '0', '3', '1.0', '1.0', '33.983679']
['2', 'All-Bran', 'K', 'C', '70', '4', '1', '260', '9.0', '7.0', '5', '320', '25', '3', '1.0', '0.33', '59.425505']
['3', 'All-Bran with Extra Fiber', 'K', 'C', '50', '4', '0', '140', '14.0', '8.0', '0', '330', '25', '3', '1.0', '0.5', '93.704912']
['4', 'Almond Delight', 'R', 'C', '110', '2', '2', '200', '1.0', '14.0', '8', '-1', '25', '3', '1.0', '0.75', '34.384843']
['5', 'Apple Cinnamon Cheerios', 'G', 'C', '110', '2', '2', '180', '1.5', '10.5', '10', '70', '25', '1', '1.0', '0.75', '29.509541']
['6', 'Apple Jacks', 'K', 'C', '110', '2', '0', '125', '1.0', '11.0', '14', '30', '25', '2', '1.0', '1.0', '33.174094']
['7', 'Basic 4', 'G', 'C', '130', '3', '2', '210', '2.0', '18.0', '8', '100', '25', '3', '1.33', '0.75', '37.038562']
['8', 'Bran Chex', 'R', 'C', '90', '2', '1', '200', '4.0', '15.0', '6', '125', '25', '1', '1.0', '0.67', '49.120253']
['9', 'Bran Flakes', 'P', 'C', '90', '3', '0', '210', '5.0', '13.0', '5', '190', '25', '3', '1.0', '0.67', '53.313813']

In [143]:
f.close()

In [175]:
import json
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""
obj

'\n{"name": "Wes",\n "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],\n "pet": null,\n "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},\n              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]\n}\n'

In [176]:
data1 = json.loads(obj)
data1

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [177]:
json.dumps(data1) # coverts file back to json

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [178]:
data1["cities_lived"]
# we can access data by using the indexes

['Akron', 'Nashville', 'New York', 'San Francisco']

In [179]:
#to coveret json to dataframe
df = pd.DataFrame(data1["siblings"], columns=["name", "age", "hobbies"])
df

    name  age            hobbies
0  Scott   34  [guitars, soccer]
1  Katie   42      [diving, art]

In [201]:
df1 = pd.read_json("myjson.json")
df1

,Unnamed: 0,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.00,0.33,68.402973
1,1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.00,1.00,33.983679
2,2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.00,0.33,59.425505
3,3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.00,0.50,93.704912
4,4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.00,0.75,34.384843
5,5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.00,0.75,29.509541
6,6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094
7,7,Basic 4,G,C,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562
8,8,Bran Chex,R,C,90,2,1,200,4.0,15.0,6,125,25,1,1.00,0.67,49.120253
9,9,Bran Flakes,P,C,90,3,0,210,5.0,13.0,5,190,25,3,1.00,0.67,53.313813

In [190]:
# data -> csv
# data1 -> json
# converting csv to json. Creating function
def convert_csv_to_json(csv_file_path, json_file_path):
    df = pd.read_csv("cereal.csv")
    df.to_json("myjson.json", orient="records")

In [193]:
df1 = convert_csv_to_json("cereal.csv","myjson.json")
df1

In [194]:
# Xlml files
from lxml import objectify
path = "myxlml.xml"
with open(path) as f:
    parsed = objectify.parse(f)

In [195]:
root = parsed.getroot()

In [199]:
df2 = pd.read_xml("myxlml.xml")
df2

,id,author,title,genre,price,publish_date,description
0,bk101,"Gambardella, Matthew",XML Developer's Guide,Computer,44.95,2000-10-01,An in-depth look at creating applications \n ...
1,bk102,"Ralls, Kim",Midnight Rain,Fantasy,5.95,2000-12-16,"A former architect battles corporate zombies, ..."
2,bk103,"Corets, Eva",Maeve Ascendant,Fantasy,5.95,2000-11-17,After the collapse of a nanotechnology \n ...
3,bk104,"Corets, Eva",Oberon's Legacy,Fantasy,5.95,2001-03-10,"In post-apocalypse England, the mysterious \n ..."
4,bk105,"Corets, Eva",The Sundered Grail,Fantasy,5.95,2001-09-10,"The two daughters of Maeve, half-sisters, \n ..."
...,...,...,...,...,...,...,...
7,bk108,"Knorr, Stefan",Creepy Crawlies,Horror,4.95,2000-12-06,"An anthology of horror stories about roaches,\..."
8,bk109,"Kress, Peter",Paradox Lost,Science Fiction,6.95,2000-11-02,After an inadvertant trip through a Heisenberg...
9,bk110,"O'Brien, Tim",Microsoft .NET: The Programming Bible,Computer,36.95,2000-12-09,Microsoft's .NET initiative is explored in \n ...
10,bk111,"O'Brien, Tim",MSXML3: A Comprehensive Guide,Computer,36.95,2000-12-01,The Microsoft MSXML3 parser is covered in \n ...
11,bk112,"Galos, Mike",Visual Studio 7: A Comprehensive Guide,Computer,49.95,2001-04-16,Microsoft Visual Studio 7 is explored in depth...

Binary Data Formats

In [6]:
# to store data in binary format is by using Python's built in function: pickle method
import pandas as pd
data_pkl = pd.read_pickle("clean_06_02_24.pkl").head(10)

In [7]:
data_pkl

,[1:0],[1:1],[1:2],[1:3],[1:4],[1:5],[1:6],[1:7],[1:8],[1:9],...,[26.115],[26.116],[26.117],[26.118],[26.119],[26.120],[26.121],[26.122],[26.123],[11:30]
Time,,,,,,,,,,,,,,,,,,,,,
2024-02-06 02:34:55.870,12749,28012,22065,19450,9.932680e-32,1.541310e-33,9,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN
2024-02-06 02:34:56.870,12749,28012,22065,19450,1.541730e+26,2.358670e-38,1,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN
2024-02-06 02:34:57.870,12749,28012,22065,24679,2.586600e+33,-1.061160e+37,-4,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN
2024-02-06 02:34:58.870,12749,28012,22065,24679,-3.776340e+22,-4.654690e-10,-81,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN
2024-02-06 02:34:59.870,12749,28012,27294,24679,-4.252430e+37,9.476850e-38,2,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN
2024-02-06 02:35:00.870,12749,28012,27294,24679,-5.118670e+02,7.031020e-41,0,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN
2024-02-06 02:35:01.870,12749,28012,27294,24679,-1.992580e+00,9.686070e-35,7,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN
2024-02-06 02:35:02.870,12749,28012,27294,29909,6.465500e-27,NaN,-2,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN
2024-02-06 02:35:03.870,12749,28012,27294,29909,-1.013530e+31,1.648100e-12,-6357,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN
2024-02-06 02:35:04.870,12749,28012,27294,29909,-1.038160e+34,1.516020e-36,4,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN

In [8]:
# pickle is recommended only as a short-term storage format, because it is hard to guarantee its stablility.
# an object pickled today may not be unpickled in later version of a library

Reading Microsoft Excel Files

In [16]:
# pandas.ExcelFile class or pandas.read_excel function
# internally add-ons packages like xlrd and openpyxl are required to read excel file
# first: pip install xlrd and openpyxl

Interacting with Web APIs

In [61]:
import requests

url = "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction"
resp = requests.get(url)
resp.raise_for_status()
resp
data_api = resp.json

In [66]:
data_api.__type_params__

()

In [60]:
issues = pd.DataFrame(data_api, columns=["number"])
issues

ValueError: DataFrame constructor not properly called!